#!/bin/bash

# Update the system
yum update -y

# Install Java 17 JDK using Amazon Corretto
yum install -y java-17-amazon-corretto-devel

# Verify Java installation
java -version

# Create new user t6admin and add to wheel group for sudo access
useradd -m t6admin
echo 't6admin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/t6admin

# Ensure SSH directory exists for t6admin
mkdir -p /home/t6admin/.ssh
chmod 700 /home/t6admin/.ssh
chown t6admin:t6admin /home/t6admin/.ssh

# Add authorized_keys for SSH access with the provided keys
cat <<EOF > /home/t6admin/.ssh/authorized_keys
ssh key1
ssh key2

EOF

# Set the correct permissions for the authorized_keys file
chmod 600 /home/t6admin/.ssh/authorized_keys

# Change ownership of the .ssh directory and its contents to t6admin
chown -R t6admin:t6admin /home/t6admin/.ssh
